### ISSUE TITLE
Check first, update only when needed

### ISSUE THREAD

**Issue by degudejung** [ZoeyVid/ipv64-updater#34]
Hallo Ihr beiden,
danke für dieses Script!

I like it for its simplicity and because it needs no root privileges to get the (non-cron) job done. 

My problem with it is that I run out of my "DynDNS Update Limit / 24h" at ipv64 because it don't check if an update is necessary (IP change) or not (IP same).

So in case you consider updating this in the future, that feature would be highly appreciated.

Thanks

**Comment by Zoey2936** [comment]
The limit is per request? I always thought is is per ip range

**Comment by degudejung** [comment]
Don‘t know how it does the counting exactly, but my understanding is that every time you call the update.php it „costs“ you 1/1024 per day. So if you do a 5m cycle, you are limited to 3 prefixes/domains or you(r script) will run into overcommitting. 

I tried forking and inserting the logic of alcapone1933 for pre-checking but since I never coded before, that was beyond what I could do on a night.

**Comment by Zoey2936** [comment]
hello, this is now supported, but you need to add the DUD env as per compose.yaml, please report back if it works

**Comment by degudejung** [comment]
Hi,
first of all great that you picked up on this so quickly. Thanks.

Here's how it looks to me:
- your new dig checks do not affect the limit now
- when the IP changes, it updates the A-record
- since you only write to /tmp/IPv4.json after an update, the container appears "unhealthy" until the first update (which could be days/weeks)
- don't know why you say "no prefixes/sub-domains" - I do just that and it works fine 

It took me a while to see that it's really "DUDs" instead of "DUD" but that was just me.

**Comment by Zoey2936** [comment]
sorry, I renamed DUD to DUDs (plural) to support multiple domain when using the account key
what do you mean with the dig check? it worked in my tests
but for the health check you are right, maybe there should be one update in any case, I will add it

**Comment by Zoey2936** [comment]
with the prefixes, it works when using the record key, domain or account key will not work

**Comment by degudejung** [comment]
ok, good! 

I tested your last night update. Now, it remains unhealthy even after a successful update. The healthcheck.sh accepts only "success" as the sole positive expression. In fact, ipv64 returns "good" or "nochg" nowadays, so your condition is not met. Maybe try "success|good|nochg" instead?

You helped me  in another way though. Only by your comment "use CNAME or let me know why" I learnt that I really only need to update one prefix and point all the other subdomains to the one I update using a CNAME. That was the solution I really needed. Now I can simply update ipv64 with the regular tools in pfsense etc. Thank you.

**Comment by Zoey2936** [comment]
Not sure, the response has two ports: suscsefull or not and if succesessfull if something changed or not, and I think the healthcheck should be good even if ip did not changed, or?

And yes CNAME is one of the best DNS record types, even with static ips (only one entrie per subdomain instead of two for A and AAAA)
